server:
  port: 9090
spring:
  application:
    name: spring-batch-client
  batch:
    lightmin:
      server:
        url: http://localhost:8090
      client:
        external-links:
          hystrix: http://localhost:${server.port}/hystrixdashboard
          batchtasks: http://localhost:${server.port}/batchtasks
      #default jdbc
      batch-repository-type: jdbc
      #default jdbc
      lightmin-repository-type: jdbc
      #default dataSource
      data-source-name: dataSource
      #default dataSource
      batch-data-source-name: dataSource
      #default BATCH_
      configuration-table-prefix: BATCH_
      #default BATCH_
      repository-table-prefix: BATCH_

datasource:
  source:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/uaa
  target:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3308/uaa

